<?php

namespace TopCarBundle\Repository\Cars;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\ORMException;
use TopCarBundle\Entity\Car;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metadata = null)
    {
        parent::__construct($em,
            $metadata == null ?
                new Mapping\ClassMetadata(Car::class) :
                $metadata
        );
    }

    public function insert($car)
    {
        try {
            $this->_em->persist($car);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }

    public function getFirstMostViewed()
    {
        return $this->createQueryBuilder('car')
            ->orderBy('car.viewCount', 'DESC')
            ->setMaxResults(4)
            ->getQuery()
            ->getResult();
    }

    public function remove($car)
    {
        try {
            $this->_em->remove($car);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }


}
